---
- name: Install docker from scratch
  template:
    src: "docker_install.sh.j2"
    dest: "/home/{{ ansible_user }}/install_docker.sh"

- name: "Run docker script"
  command: "sh /home/{{ ansible_user }}/install_docker.sh"
  when: ansible_docker0 is undefined
    
- name: "Start docker"
  service:
    name: docker
    enabled: yes
    state: started
